; ######################
; # BARS CONFIGURATION #
; ######################

[bar/main]
; Bar position (top/bottom).
bottom = false

; Type of module centering, if false the center will change with the number of modules.
fixed-center = true

; Width and height of the bar.
width = 100%
height = 40

; Pixel offset.
offset-x = 0
offset-y = 5

; Background color. Background color is set to transparent.
background = ${color.transparent}
; background = #00000000

; Foreground color (text color and other elements). Colors read from .Xresources on the config.ini file.
foregound = {color.foreground}

; Radius for the rounded corners.
radius-top = 0
radius-bot = 0

; No idea what this is lmao.
overline-size = 2
overline-color = ${color.alert}

; Bar borders.
border-top-size = 3
border-color = ${color.transparent}
; border-color = ${color.pink}

; Bar padding.
padding = 0
padding-left = 0
padding-right = 0

; Bar fonts.
font-0 = "CaskaydiaCove Nerd Font:size=11;3"
font-1 = Font Awesome 5 Free: style=Solid: pixelsize=11
font-2 = Font Awesome 5 Brands: pixelsize=11
font-3 = Material Icons: style=Regular: pixelsize=12.5
font-4 = "CaskaydiaCove Nerd Font:size=17;4"
font-5 = "CaskaydiaCove Nerd Font:size=24;6"

; Bar modules.
; All modules are written on polybar/modules.ini
; Available modules: 
;   cStart : rounded border start
;   cEnd : rounded border end
;   bspwm : bspwm workspaces
;   space : just a space to keep everything not touching
;   xwindow : name of the current window
;   date : displays the current time
;   date_full : displays the current week day and month day
;   wlan : displays network status
;   battery : displays battery status
;   xbacklight : displays keyboard backlight status
;   pulseaudio :  displays audio levels status
;   powermenu : opens a rofi powermenu
modules-left = space cStart bspwm cEnd space cStart window cEnd
modules-center = cStart date cEnd
modules-right = wlan battery xbacklight pulseaudio powermenu

; Restack the bar window and put it above the selected window manager's root.
wm-restack = bspwm
dim-value = 1.0

; Enable support for inter-process messaging.
enable-ipc = true

; System tray settings.
tray-position = right
tray-detached = false
tray-maxsize = 16
tray-background = ${color.background-alt}
tray-padding = 2
tray-scale = 1

[bar/base]

; Bar fonts.
font-0 = "CaskaydiaCove Nerd Font:size=11;3"
font-1 = Font Awesome 5 Free: style=Solid: pixelsize=11
font-2 = Font Awesome 5 Brands: pixelsize=11
font-3 = Material Icons: style=Regular: pixelsize=12.5
font-4 = "CaskaydiaCove Nerd Font:size=17;4"
font-5 = "CaskaydiaCove Nerd Font:size=16;5"

; Bar position (top/bottom).
bottom = false

; Type of module centering, if false the center will change with the number of modules.
fixed-center = true

; Bar height.
height = 40

; Radius for the rounded corners.
radius = 20.0

; No idea what this is lmao.
overline-size = 2
overline-color = ${color.alert}

; Bar borders.
border-top-size = 3
border-color = ${color.transparent}

; Bar padding.
padding = 0
padding-left = 0
padding-right = 0

[bar/workspaces]

# Inheritance.
inherit = bar/base

; Width of the bar.
width = 10.5%

; Pixel offset.
offset-x = 11
offset-y = 5

; Background color.
background = ${color.background}

; Foreground color (text color and other elements). Colors read from .Xresources on the config.ini file.
foregound = {color.foreground}

modules-left = bspwm

[bar/window]

# Inheritance.
inherit = bar/base

; Width of the bar.
width = 17%

; Pixel offset.
offset-x = 220
offset-y = 5

; Background color.
background = ${color.background}

; Foreground color (text color and other elements). Colors read from .Xresources on the config.ini file.
foregound = {color.foreground}

modules-left = window

[bar/time]

# Inheritance.
inherit = bar/base

; Width of the bar.
width = 5.15%

; Pixel offset.
offset-x = 47.5%
offset-y = 5

; Background color.
background = ${color.background}

; Foreground color (text color and other elements). Colors read from .Xresources on the config.ini file.
foregound = {color.foreground}

modules-left = date

[bar/system]

# Inheritance.
inherit = bar/base

; Width of the bar.
width = 19%

; Pixel offset.
offset-x = 77.7%
offset-y = 5

; Background color.
background = ${color.background}

; Foreground color (text color and other elements). Colors read from .Xresources on the config.ini file.
foregound = {color.foreground}

modules-left = network battery backlight audio

[bar/power]

# Inheritance.
inherit = bar/base

; Width of the bar.
width = 2.2%

; Pixel offset.
offset-x = 97.2%
offset-y = 5

; Background color.
background = ${color.background}

; Foreground color (text color and other elements). Colors read from .Xresources on the config.ini file.
foregound = {color.foreground}

modules-left = powermenu

; Configuration settings for polybar bar on EndeavourOS + BSPWM by github.com/gweebg and based off github.com/umgbhalla .