; #########################
; # MODULES CONFIGURATION #
; #########################

; Available modules: 
;   cStart : rounded border start
;   cEnd : rounded border end
;   bspwm : bspwm workspaces
;   space : just a space to keep everything not touching
;   xwindow : name of the current window
;   date : displays the current time
;   date_full : displays the current week day and month day
;   wlan : displays network status
;   battery : displays battery status
;   xbacklight : displays keyboard backlight status
;   pulseaudio :  displays audio levels status
;   powermenu : opens a rofi powermenu

; Left modules :

[module/bspwm]
type = internal/bspwm

pin-workspaces = true
strip-wsnumbers = true
index-sort = true

enable-click = true
enable-scroll = true

wrapping-scroll = false
reverse-scroll = true

format = <label-state> <label-mode>

format-font = 5

label-focused = "  "

label-focused-foreground = ${color.pink}
label-focused-background = ${color.background-alt}
label-focused-padding = 0

label-occupied = "  "
label-occupied-foreground = ${color.blue}
label-occupied-background = ${color.background-alt}
label-occupied-padding = 0

label-empty = "  "
label-empty-foreground = ${color.gray}
label-empty-background = ${color.background-alt}
label-empty-padding = 0

label-urgent = "  "
label-urgent-foreground = ${color.pink}
label-urgent-background = ${color.background-alt}
label-urgent-padding = 1

label-mode = %mode%
label-mode-padding = 1
label-mode-foreground = ${color.foreground}
label-mode-background = ${color.background-alt}

[module/window]
type = internal/xwindow
label = "  %title:0:30:...%" 

label-background = ${color.background}
label-empty = "              (empty)"
label-empty-foreground = ${color.blue}

[module/window_icon]
type = custom/text

content = "  "
content-font = 6
content-foreground = ${color.background}
content-background = ${color.blue}

; Center modules :

[module/date]
type = internal/date
interval = 5

date = 
date-alt = " %d-%m-%Y"

time = %H:%M
time-alt = %H:%M

format-prefix-foreground = ${colors.foreground-alt}

label = "   %time%"
label-background = ${color.background}

[module/date_icon]
type = custom/text

content = "  "
content-font = 6
content-foreground = ${color.background}
content-background = ${color.blue}

[module/powermenu]
type = custom/text

content = " 襤 "
content-font = 5

click-left = ~/.config/rofi/applets/android/powermenu.sh

[module/wired-network]
type = internal/network
interface = eth0

[module/wireless-network]
type = internal/network
interface = wlan0

[module/network]
type = internal/network

interface = wlan0
interval = 3.0

accumulate-stats = true
unknown-as-up = true

format-connected = <ramp-signal><label-connected>

label-connected = " %upspeed% "

ramp-signal-0 = "  睊 "
ramp-signal-1 = "  直 "
ramp-signal-2 = "   " 

format-disconnected = <label-disconnected>
label-disconnected = " 睊  %upspeed% "

label-connected-background = ${color.blue}
label-disconnected-background = ${color.blue}
ramp-signal-background = ${color.blue}

label-disconnected-foreground = ${color.pink}

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 95

format-charging = <animation-charging><label-charging>
label-charging = "%percentage%% "

format-discharging = <ramp-capacity><label-discharging>
label-discharging = "%percentage%%  "

format-full-prefix = "   "

ramp-capacity-0 = "   "
ramp-capacity-1 = "   "
ramp-capacity-2 = "   " 
ramp-capacity-3 = "   "
ramp-capacity-4 = "   "
ramp-capacity-5 = "   "
ramp-capacity-6 = "   "
ramp-capacity-7 = "   "
ramp-capacity-8 = "   "
ramp-capacity-9 = "   "

animation-charging-0 = 
animation-charging-framerate = 750

; animation-charging-background = ${color.pink}
; label-charging-background = ${color.pink}
; label-discharging-background = ${color.pink}
; ramp-capacity-background = ${color.pink}

[module/backlight]
type= internal/xbacklight
enable-scroll = true
format = <ramp><label>

label = "%percentage%%  "

ramp-0 = "   "  
ramp-1 = "   "
ramp-2 = "   "
ramp-3 = "   "

label-background = ${color.blue}
ramp-background = ${color.blue}

[module/audio]
type = internal/pulseaudio

format-volume = <ramp-volume><label-volume>

ramp-volume-0 = "   "
ramp-volume-1 = "   "
ramp-volume-2 = "   "

label-volume = %percentage%%
label-volume-foreground = ${color.foreground}

label-muted = "   ﱝ "
label-muted-foreground = ${color.pink}
label-muted-font = 6

click-left = pavucontrol